# Generated by Django 4.2.4 on 2023-08-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
